---
abstract: 'Generate signed XML documents as SAML responses for'
author:
  - 'Manni Heumann (saml at lxxi dot org)'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-SAML-Response
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Crypt::OpenSSL::Bignum: 0
  Crypt::OpenSSL::DSA: 0
  Crypt::OpenSSL::RSA: 0
  Date::Format: 0
  Digest::SHA: 0
  File::Which: 0
  Google::SAML::Request: 0
  Test::Exception: 0
  Test::More: 0
  XML::CanonicalizeXML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mannih/cpan/tree/master/Google-SAML-Response/
version: 0.11
