# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Google-SAML-Response
version:      0.04
version_from: lib/Google/SAML/Response.pm
installdirs:  site
requires:
    Carp:                          0
    Crypt::OpenSSL::Bignum:        0
    Crypt::OpenSSL::RSA:           0
    Date::Format:                  0
    Digest::SHA:                   0
    Google::SAML::Request:         0
    Test::Exception:               0
    Test::More:                    0
    XML::CanonicalizeXML:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
