--- #YAML:1.0
name:                Google-SAML-Response
version:             0.06
abstract:            Generate signed XML documents as SAML responses for
license:             ~
author:              
    - Manni Heumann <saml@lxxi.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Crypt::OpenSSL::Bignum:        0
    Crypt::OpenSSL::DSA:           0
    Crypt::OpenSSL::RSA:           0
    Date::Format:                  0
    Digest::SHA:                   0
    File::Which:                   0
    Google::SAML::Request:         0
    Test::Exception:               0
    Test::More:                    0
    XML::CanonicalizeXML:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
