--- #YAML:1.0
name:               Google-SAML-Response
version:            0.10
abstract:           Generate signed XML documents as SAML responses for
author:
    - Manni Heumann <saml@lxxi.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Crypt::OpenSSL::Bignum:  0
    Crypt::OpenSSL::DSA:  0
    Crypt::OpenSSL::RSA:  0
    Date::Format:         0
    Digest::SHA:          0
    File::Which:          0
    Google::SAML::Request:  0
    Test::Exception:      0
    Test::More:           0
    XML::CanonicalizeXML:  0
resources:
    repository:  http://github.com/mannih/cpan/tree/master/Google-SAML-Response/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
